name: Release

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: "softprops/action-gh-release@v1"
        with:
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: release
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Run build
        run: |
          cargo build --all --release
          strip --strip-all ./target/release/dendron-handler
          mv ./target/release/dendron-handler ./target/release/dendron-handler-linux

      - name: Upload release
        id: upload-release-linux
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_paths: '["./target/release/dendron-handler-linux"]'

  build-macos:
    runs-on: macos-latest
    permissions: write-all
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Run build
        run: |
          cargo build --all --release
          mv ./target/release/dendron-handler ./target/release/dendron-handler-macos

      - name: Upload release
        id: upload-release-linux
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_paths: '["./target/release/dendron-handler-macos"]'

  build-windows:
    runs-on: windows-2019
    permissions: write-all
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Run build
        run: cargo build --all --release

      - name: Upload release
        id: upload-release-windows
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_paths: '["./target/release/dendron-handler.exe"]'
